preset: laravel

enabled:
  - align_equals
  - uppercase_constants

disabled:
  - single_class_element_per_statement
  - self_accessor
  - concat_without_spaces
  - function_declaration
  - unalign_equals
  - no_blank_lines_after_class_opening
  - lowercase_constants