language: php

php:
  - 7.4
  - 8.0
  - 8.2

env:
    - LARAVEL='^6.0'
    - LARAVEL='^7.0'
    - LARAVEL='^8.0'
    - LARAVEL='^9.0'
    - LARAVEL='^10.0'

matrix:
  exclude:
    - php: 7.4
      env: LARAVEL='^9.0'
    - php: 7.4
      env: LARAVEL='^10.0'
    - php: 8.0
      env: LARAVEL='^10.0'

install:
  - composer require "laravel/framework:${LARAVEL}" --prefer-dist --no-interaction --no-suggest
  - composer install --prefer-dist --no-interaction --no-suggest

script:
  - vendor/bin/phpunit

cache:
  directories:
    - $HOME/.composer/cache